export const SHIP_REGISTRATION_ROLES = {
	FABRICATOR: 'FABRICATOR',
	HARVESTER: 'HARVESTER',
	HAULER: 'HAULER',
	INTERCEPTOR: 'INTERCEPTOR',
	EXCAVATOR: 'EXCAVATOR',
	TRANSPORT: 'TRANSPORT',
	REPAIR: 'REPAIR',
	SURVEYOR: 'SURVEYOR',
	COMMAND: 'COMMAND',
	CARRIER: 'CARRIER',
	PATROL: 'PATROL',
	SATELLITE: 'SATELLITE',
	EXPLORER: 'EXPLORER',
	REFINERY: 'REFINERY',
} as const;

export const SHIP_REGISTRATION_ROLES_LIST = Object.values(SHIP_REGISTRATION_ROLES);

export const SHIP_NAV_ROUTE_WAYPOINTS = {
	PLANET: 'PLANET',
	GAS_GIANT: 'GAS_GIANT',
	MOON: 'MOON',
	ORBITAL_STATION: 'ORBITAL_STATION',
	JUMP_GATE: 'JUMP_GATE',
	ASTEROID_FIELD: 'ASTEROID_FIELD',
	NEBULA: 'NEBULA',
	DEBRIS_FIELD: 'DEBRIS_FIELD',
	GRAVITY_WELL: 'GRAVITY_WELL',
} as const;

export const SHIP_NAV_ROUTE_WAYPOINTS_LIST = Object.values(SHIP_NAV_ROUTE_WAYPOINTS);

export const SHIP_NAV_STATUS = {
	IN_TRANSIT: 'IN_TRANSIT',
	IN_ORBIT: 'IN_ORBIT',
	DOCKED: 'DOCKED',
} as const;

export const SHIP_VAR_STATUS_LIST = Object.values(SHIP_NAV_STATUS);

export const SHIP_NAV_FLIGHT_MODES = {
	DRIFT: 'DRIFT',
	STEALTH: 'STEALTH',
	CRUISE: 'CRUISE',
	BURN: 'BURN',
} as const;

export const SHIP_NAV_FLIGHT_MODES_LIST = Object.values(SHIP_NAV_FLIGHT_MODES);

export const SHIP_CREW_ROTATIONS = {
	STRICT: 'STRICT',
	RELAXED: 'RELAXED',
} as const;

export const SHIP_CREW_ROTATIONS_LIST = Object.values(SHIP_CREW_ROTATIONS);

export const SHIP_FRAME_SYMBOLS = {
	FRAME_PROBE: 'FRAME_PROBE',
	FRAME_DRONE: 'FRAME_DRONE',
	FRAME_INTERCEPTOR: 'FRAME_INTERCEPTOR',
	FRAME_RACER: 'FRAME_RACER',
	FRAME_FIGHTER: 'FRAME_FIGHTER',
	FRAME_FRIGATE: 'FRAME_FRIGATE',
	FRAME_SHUTTLE: 'FRAME_SHUTTLE',
	FRAME_EXPLORER: 'FRAME_EXPLORER',
	FRAME_MINER: 'FRAME_MINER',
	FRAME_LIGHT_FREIGHTER: 'FRAME_LIGHT_FREIGHTER',
	FRAME_HEAVY_FREIGHTER: 'FRAME_HEAVY_FREIGHTER',
	FRAME_TRANSPORT: 'FRAME_TRANSPORT',
	FRAME_DESTROYER: 'FRAME_DESTROYER',
	FRAME_CRUISER: 'FRAME_CRUISER',
	FRAME_CARRIER: 'FRAME_CARRIER',
} as const;

export const SHIP_FRAME_SYMBOLS_LIST = Object.values(SHIP_FRAME_SYMBOLS);

export const SHIP_REACTORS = {
	REACTOR_SOLAR_I: 'REACTOR_SOLAR_I',
	REACTOR_FUSION_I: 'REACTOR_FUSION_I',
	REACTOR_FISSION_I: 'REACTOR_FISSION_I',
	REACTOR_CHEMICAL_I: 'REACTOR_CHEMICAL_I',
	REACTOR_ANTIMATTER_I: 'REACTOR_ANTIMATTER_I',
} as const;

export const SHIP_REACTORS_LIST = Object.values(SHIP_REACTORS);

export const SHIP_ENGINES = {
	ENGINE_IMPULSE_DRIVE_I: 'ENGINE_IMPULSE_DRIVE_I',
	ENGINE_ION_DRIVE_I: 'ENGINE_ION_DRIVE_I',
	ENGINE_ION_DRIVE_II: 'ENGINE_ION_DRIVE_II',
	ENGINE_HYPER_DRIVE_I: 'ENGINE_HYPER_DRIVE_I',
} as const;

export const SHIP_ENGINES_LIST = Object.values(SHIP_ENGINES);

export const SHIP_MODULES = {
	MODULE_MINERAL_PROCESSOR_I: 'MODULE_MINERAL_PROCESSOR_I',
	MODULE_CARGO_HOLD_I: 'MODULE_CARGO_HOLD_I',
	MODULE_CREW_QUARTERS_I: 'MODULE_CREW_QUARTERS_I',
	MODULE_ENVOY_QUARTERS_I: 'MODULE_ENVOY_QUARTERS_I',
	MODULE_PASSENGER_CABIN_I: 'MODULE_PASSENGER_CABIN_I',
	MODULE_MICRO_REFINERY_I: 'MODULE_MICRO_REFINERY_I',
	MODULE_ORE_REFINERY_I: 'MODULE_ORE_REFINERY_I',
	MODULE_FUEL_REFINERY_I: 'MODULE_FUEL_REFINERY_I',
	MODULE_SCIENCE_LAB_I: 'MODULE_SCIENCE_LAB_I',
	MODULE_JUMP_DRIVE_I: 'MODULE_JUMP_DRIVE_I',
	MODULE_JUMP_DRIVE_II: 'MODULE_JUMP_DRIVE_II',
	MODULE_JUMP_DRIVE_III: 'MODULE_JUMP_DRIVE_III',
	MODULE_WARP_DRIVE_I: 'MODULE_WARP_DRIVE_I',
	MODULE_WARP_DRIVE_II: 'MODULE_WARP_DRIVE_II',
	MODULE_WARP_DRIVE_III: 'MODULE_WARP_DRIVE_III',
	MODULE_SHIELD_GENERATOR_I: 'MODULE_SHIELD_GENERATOR_I',
	MODULE_SHIELD_GENERATOR_II: 'MODULE_SHIELD_GENERATOR_II',
} as const;

export const SHIP_MODULES_LIST = Object.values(SHIP_MODULES);

export const SHIP_MOUNTS = {
	MOUNT_GAS_SIPHON_I: 'MOUNT_GAS_SIPHON_I',
	MOUNT_GAS_SIPHON_II: 'MOUNT_GAS_SIPHON_II',
	MOUNT_GAS_SIPHON_III: 'MOUNT_GAS_SIPHON_III',
	MOUNT_SURVEYOR_I: 'MOUNT_SURVEYOR_I',
	MOUNT_SURVEYOR_II: 'MOUNT_SURVEYOR_II',
	MOUNT_SURVEYOR_III: 'MOUNT_SURVEYOR_III',
	MOUNT_SENSOR_ARRAY_I: 'MOUNT_SENSOR_ARRAY_I',
	MOUNT_SENSOR_ARRAY_II: 'MOUNT_SENSOR_ARRAY_II',
	MOUNT_SENSOR_ARRAY_III: 'MOUNT_SENSOR_ARRAY_III',
	MOUNT_MINING_LASER_I: 'MOUNT_MINING_LASER_I',
	MOUNT_MINING_LASER_II: 'MOUNT_MINING_LASER_II',
	MOUNT_MINING_LASER_III: 'MOUNT_MINING_LASER_III',
	MOUNT_LASER_CANNON_I: 'MOUNT_LASER_CANNON_I',
	MOUNT_MISSILE_LAUNCHER_I: 'MOUNT_MISSILE_LAUNCHER_I',
	MOUNT_TURRET_I: 'MOUNT_TURRET_I',
} as const;

export const SHIP_MOUNTS_LIST = Object.values(SHIP_MOUNTS);

export const SHIP_DEPOSITS = {
	QUARTZ_SAND: 'QUARTZ_SAND',
	SILICON_CRYSTALS: 'SILICON_CRYSTALS',
	PRECIOUS_STONES: 'PRECIOUS_STONES',
	ICE_WATER: 'ICE_WATER',
	AMMONIA_ICE: 'AMMONIA_ICE',
	IRON_ORE: 'IRON_ORE',
	COPPER_ORE: 'COPPER_ORE',
	SILVER_ORE: 'SILVER_ORE',
	ALUMINUM_ORE: 'ALUMINUM_ORE',
	GOLD_ORE: 'GOLD_ORE',
	PLATINUM_ORE: 'PLATINUM_ORE',
	DIAMONDS: 'DIAMONDS',
	URANITE_ORE: 'URANITE_ORE',
	MERITIUM_ORE: 'MERITIUM_ORE',
} as const;

export const SHIP_DEPOSITS_LIST = Object.values(SHIP_DEPOSITS);
